apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: favourite-service
  name: favourite-service
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    io.kompose.service: favourite-service
