### POST request to authenticate
POST http://localhost:8080/app/api/authenticate
Content-Type: application/json

{
  "username": "markcus",
  "password": "password"
}

> {%
    // Access the specific field 'token' from the response object
    client.global.set("token", response.body.jwtToken);
    client.log("Clean Token set: " + client.global.get("token"));
%}

###